### ISSUE TITLE
如何处理数据

### ISSUE THREAD

**Issue by 18222278799** [xiangrongzeng/copy_re#12]
您好，有将原始数据处理成各种json文件的程序么，不知道您怎么进行处理的

**Comment by xiangrongzeng** [comment]
应该还有，我下班了回去找找吧，现在手头上没有




------------------ 原始邮件 ------------------
发件人: "Zhang tianlin"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 上午10:14
收件人: "xiangrongzeng/copy_re"<copy_re@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [xiangrongzeng/copy_re] 如何处理数据 (#12)




您好，有将原始数据处理成各种json文件的程序么，不知道您怎么进行处理的

**Comment by 18222278799** [comment]
十分感谢学长

**Comment by xiangrongzeng** [comment]
已经更新了

**Comment by 18222278799** [comment]
thanks very much
