### ISSUE TITLE
一些疑惑

### ISSUE THREAD

**Issue by Fengfeng1024** [xiangrongzeng/copy_re#13]
您好！打扰了，这几天拜读了您的论文，被论文巧妙的构思、扎实的工作深深折服了。看论文的时候仍存在一些疑问，希望得到您的解答。
- 17年ACL这篇《Joint Extraction of Entities and Relations Based on a Novel Tagging Scheme》提到的NYT数据集已经提供有测试集，为什么您还要自己划分呢？还有一点我不明白的是，为什么要过滤长度大于100的句子？
- 您在论文中提到抽取三元组，但是您的论文只能抽取实体的最后一个单词。
希望能得到您的答复。谢谢~

**Comment by xiangrongzeng** [comment]
1、那个测试集规模比较小且大部分不包括重叠的情况，所以我们自己划分了训练集和测试集
2、目前模型只能抽取一个实体的一个词。

**Comment by Fengfeng1024** [comment]
非常感谢！
