### ISSUE TITLE
What is the accuracy, precision report in paper?

### ISSUE THREAD

**Issue by edfall** [xiangrongzeng/copy_re#18]
- if the triplet entities contain multiple words, your sequence decoding pipeline will never get the right triplet out, so whether the multiple word triplets are all count wrong? 
- or you just evaluate it based on the inaccruate tagging target?

**Comment by yuwl798180** [comment]
agree with you, just look at your code, have the same question.

**Comment by xiangrongzeng** [comment]
- For the triplet entities contain multiple words, this model cannot extract the complete entity. We only consider the last word of the entity (with multiple words). 
- We mentioned this in our paper section 4.3
- How to extract the complete entity during the overlapping relation extraction remains an open chanllenge and there are several papers focuing on this problem.
