### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by zhentaoCoding** [xiangrongzeng/copy_re#4]
hi, Dr Zeng.When I use nyt dataset to train.I can't foud the files shown in the next img.Could you upload them?
![image](https://user-images.githubusercontent.com/5669444/47077438-861cce80-d233-11e8-8fad-540daf4b10e6.png)

**Comment by ZincW** [comment]
The author uploaded the processed data so raw_data is not necessary. You can comment it directly.
