### ISSUE TITLE
f1/precision/recall 

### ISSUE THREAD

**Issue by wangxshu** [xiangrongzeng/copy_re#5]
您好！请问我用默认设置训练webnlg的时候f1/precision/recall 只有0.218 0.182 0.199 会是什么原因呢。我尝试过将cell换成gru，然后看了上面的回答把learning rate改成0.01，也只是提升到0.352 0.358 0.346 。如果可以的话想请教一下改进的方法。

**Comment by xiangrongzeng** [comment]
Duplicate of #2 
请参考issue#2，学习率设置为0.001
