### ISSUE TITLE
NYT原始数据集

### ISSUE THREAD

**Issue by michael-hon** [xiangrongzeng/copy_re#6]
您好！
   请问您有NYT原始数据集（包括训练数据集、验证数据集、测试数据集）吗？能否发我一份，我的邮箱是：931558722@qq.com.
  谢谢您！

**Comment by liujian19911023** [comment]
楼上找到了吗，没有原始数据集，不知道数据集中的id怎么对应的。

**Comment by michael-hon** [comment]
> 楼上找到了吗，没有原始数据集，不知道数据集中的id怎么对应的。

还没有！楼主您找到了吗？按照论文的说法，好像作者是先过滤所有仅包含None关系的句子，我过滤CoType论文发布的数据集（也是NYT），也是得到6w多条句子

**Comment by xiangrongzeng** [comment]
数据集中id的对应关系其实可以根据[data_prepare.py](https://github.com/xiangrongzeng/copy_re/blob/master/data_prepare.py#L26)中的Data类看出来。因为我在预处理数据的时候读入原始文本输出预处理后的id数据，并没有保存中间的预处理后的文本数据，所以没有提供预处理后的文本文件。

**Comment by ee2r2fd** [comment]
同求原始数据集

**Comment by xiangrongzeng** [comment]
论文中使用的NYT原始数据已经上传，大家可以在README中找到包括Google Drive和百度网盘的下载链接。
