### ISSUE TITLE
relation facts order question？

### ISSUE THREAD

**Issue by sloth2012** [xiangrongzeng/copy_re#9]
Have you considered that relation facts order will affect the loss count？
for example：
target triplets may be like this: [(1,2,3),(4,5,6)], which should be equal to [(4,5,6), (1,2,3)]. with the way counting loss that paper mentioned, it may be quit different.

**Comment by xiangrongzeng** [comment]
Yes, I have consider this. 
Check this [function ](https://github.com/xiangrongzeng/copy_re/blob/master/evaluation.py#L68) in the code.
We use a set to store the triplets.  Therefore, {(1,2,3),(4,5,6)} is the same with {(4,5,6), (1,2,3)}.

**Comment by sloth2012** [comment]
@xiangrongzeng Sorry, i didn't notice that. thank you!
